'use client'
import {useEffect,useState} from 'react';import {useRouter} from 'next/navigation';import {ArrowLeft,ArrowRight,Check,ChevronLeft} from 'lucide-react';import {Logo} from '@/components/shell';import {QuestionnaireAnswers} from '@/types';import {cn} from '@/lib/utils'
const steps=['About You','Goals','Risk','Experience','Preferences','Review'];const empty:QuestionnaireAnswers={name:'',email:'',phone:'',country:'',age:'',goals:[],risk:'',experience:'',investingYears:'',assets:'',specialties:[],approach:'',communication:''}
const goals=['Grow my wealth','Plan for retirement','Generate income','Preserve capital','Build a financial plan','Save for a major purchase','Education planning','Other'];
const risks=[['Conservative','I prefer stability and protecting capital.'],['Moderately Conservative','I can accept limited fluctuations for some growth.'],['Balanced','I want a balance between growth and stability.'],['Growth',"I'm comfortable accepting more volatility for higher growth potential."],['Aggressive',"I'm comfortable with significant fluctuations for higher potential returns."]]
const exp=[['New to investing',"I've never invested or have very limited experience."],['Some experience',"I've made investments before but don't consider myself experienced."],['Experienced',"I'm comfortable understanding common investment products."],['Advanced','I actively manage or closely follow investments.']]
const specs=['Wealth Management','Retirement','Tax Planning','Estate Planning','Business / Entrepreneurial','Investment Planning','Other']
export default function Match(){const router=useRouter();const [step,setStep]=useState(0);const [a,setA]=useState(empty);const [tried,setTried]=useState(false);useEffect(()=>{const x=localStorage.getItem('noreva-answers');if(x)try{setA(JSON.parse(x))}catch{}},[]);useEffect(()=>{localStorage.setItem('noreva-answers',JSON.stringify(a))},[a]);const set=(k:keyof QuestionnaireAnswers,v:any)=>setA(x=>({...x,[k]:v}));const toggle=(k:'goals'|'specialties',v:string)=>setA(x=>({...x,[k]:x[k].includes(v)?x[k].filter(y=>y!==v):[...x[k],v]}));const valid=[!!a.name&&/^\S+@\S+\.\S+$/.test(a.email)&&!!a.country&&!!a.age,a.goals.length>0,!!a.risk,!!a.experience&&!!a.investingYears,!!a.assets&&a.specialties.length>0&&!!a.approach,true][step];const next=()=>{setTried(true);if(!valid)return;if(step===5){router.push('/match/loading');return}setStep(s=>s+1);setTried(false);window.scrollTo(0,0)};return <div className="min-h-screen bg-white"><header className="border-b border-green-100 bg-white"><div className="container flex h-[66px] items-center justify-between"><Logo/><span className="text-xs font-bold tracking-wide text-gray-500">ADVISOR MATCHING</span><button onClick={()=>router.push('/')} className="text-xs text-gray-500">Save & exit</button></div></header><div className="border-b bg-white"><div className="container py-5"><div className="hidden grid-cols-6 md:grid">{steps.map((s,i)=><button key={s} onClick={()=>i<step&&setStep(i)} className="relative text-left"><div className={`absolute left-4 right-0 top-3 h-px ${i<step?'bg-green-600':'bg-gray-200'} ${i===5?'hidden':''}`}/><span className={`relative flex h-7 w-7 items-center justify-center rounded-full text-[11px] ${i<step?'bg-green-600 text-white':i===step?'bg-green-600 text-white':'border border-gray-300 bg-white'}`}>{i<step?<Check size={13}/>:i+1}</span><span className={`mt-2 block text-[11px] font-bold ${i===step?'text-green-600':'text-gray-400'}`}>{s}</span></button>)}</div><div className="md:hidden"><div className="flex justify-between text-xs font-bold"><span>Step {step+1} of 6</span><span>{steps[step]}</span></div><div className="mt-3 h-1 bg-gray-200"><div className="h-full bg-green-600 transition-all" style={{width:`${(step+1)/6*100}%`}}/></div></div></div></div>
<main className="mx-auto w-full max-w-[808px] px-5 py-10 pb-48 md:py-14 md:pb-40"><button onClick={()=>step?setStep(step-1):router.push('/')} className="mb-8 flex items-center gap-1 text-xs font-bold text-gray-500"><ChevronLeft size={15}/> Back</button><section className="fade" key={step}><div className="eyebrow">Step {step+1} of 6</div><h1 className="display mt-3 text-4xl md:text-5xl">{['Let’s start with the basics.','What are you primarily looking to accomplish?','How comfortable are you with investment risk?','How would you describe your investment experience?','What should your advisor relationship look like?','Review your information.'][step]}</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-gray-600">{['A little context helps us find advisors who are relevant to you.','Choose all that apply. Your priorities help us weigh relevant specialties.','Choose the statement that feels closest to you. This does not guarantee or predict returns.','Tell us how familiar you are with common investment decisions.','Only the details useful for making a considered match.','Make sure everything feels right. You can return to any section.'][step]}</p>
{step===0&&<div className="mt-10 grid gap-5 sm:grid-cols-2"><Field label="Full Name *"><input className="field" value={a.name} onChange={e=>set('name',e.target.value)} placeholder="Your full name"/></Field><Field label="Email Address *"><input type="email" className="field" value={a.email} onChange={e=>set('email',e.target.value)} placeholder="you@example.com"/></Field><Field label="Phone Number"><input className="field" value={a.phone} onChange={e=>set('phone',e.target.value)} placeholder="Optional"/></Field><Field label="Country of Residence *"><input className="field" value={a.country} onChange={e=>set('country',e.target.value)} placeholder="Country"/></Field><Field label="Age Range *"><Select value={a.age} onChange={v=>set('age',v)} options={['18–29','30–39','40–49','50–59','60+']}/></Field></div>}
{step===1&&<Options items={goals.map(x=>[x,''])} selected={a.goals} onClick={v=>toggle('goals',v)} grid/>}
{step===2&&<Options items={risks} selected={[a.risk]} onClick={v=>set('risk',v)}/>} 
{step===3&&<div><Options items={exp} selected={[a.experience]} onClick={v=>set('experience',v)}/><div className="mt-9"><Field label="How long have you been investing? *"><Select value={a.investingYears} onChange={v=>set('investingYears',v)} options={['Less than 1 year','1–3 years','3–5 years','5–10 years','10+ years']}/></Field></div></div>}
{step===4&&<div className="mt-10 space-y-8"><Field label="Estimated investable assets *"><Select value={a.assets} onChange={v=>set('assets',v)} options={['Under $50,000','$50,000–$250,000','$250,000–$500,000','$500,000–$1M','$1M–$5M','$5M+']}/></Field><div><label className="label">Preferred advisor specialization *</label><Options items={specs.map(x=>[x,''])} selected={a.specialties} onClick={v=>toggle('specialties',v)} grid/></div><Field label="Preferred advisor approach *"><Select value={a.approach} onChange={v=>set('approach',v)} options={['Hands-on','Collaborative','Mostly independent',"I'm not sure"]}/></Field><Field label="Preferred communication"><Select value={a.communication} onChange={v=>set('communication',v)} options={['Email','Phone']}/></Field></div>}
{step===5&&<div className="mt-10 divide-y border-y border-gray-200">{[['About You',`${a.name} · ${a.email} · ${a.country}`,0],['Goals',a.goals.join(' · '),1],['Risk Profile',a.risk,2],['Experience',`${a.experience} · ${a.investingYears}`,3],['Financial Profile',a.assets,4],['Advisor Preferences',`${a.specialties.join(' · ')} · ${a.approach}`,4]].map(([t,v,n]:any)=><div key={t} className="flex items-start justify-between gap-5 py-5"><div><h3 className="text-sm font-bold">{t}</h3><p className="mt-2 text-sm text-gray-600">{v||'Not specified'}</p></div><button onClick={()=>setStep(n)} className="text-xs font-bold text-green-600">Edit</button></div>)}</div>}
{tried&&!valid&&<p role="alert" className="mt-7 text-sm font-semibold text-red-600">Please complete the required information before continuing.</p>}</section></main><div className="fixed inset-x-0 bottom-0 z-30 border-t border-gray-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-[808px] gap-3 px-5 pb-[calc(1rem+env(safe-area-inset-bottom))] pt-4"><button onClick={()=>step?setStep(step-1):router.push('/')} className="btn btn-light"><ArrowLeft size={15}/><span className="hidden sm:inline">Back</span></button><button onClick={next} aria-disabled={!valid} className={cn('btn btn-dark ml-auto w-full sm:w-auto',!valid&&'opacity-50')}>{step===5?'Find My Matches':'Continue'} <ArrowRight size={15}/></button></div></div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="label">{label}</span>{children}</label>}
function Select({value,onChange,options}:{value:string;onChange:(v:string)=>void;options:string[]}){return <select className="field" value={value} onChange={e=>onChange(e.target.value)}><option value="">Select an option</option>{options.map(x=><option key={x}>{x}</option>)}</select>}
function Options({items,selected,onClick,grid=false}:{items:string[][];selected:string[];onClick:(v:string)=>void;grid?:boolean}){return <div className={cn('mt-8 grid gap-3',grid&&'sm:grid-cols-2')}>{items.map(([t,d])=>{const active=selected.includes(t);return <button type="button" key={t} onClick={()=>onClick(t)} className={cn('flex min-h-[62px] items-center gap-4 border bg-white p-4 text-left transition',active?'border-green-300 bg-green-50':'border-gray-200 hover:border-gray-400')}><span className={cn('flex h-5 w-5 shrink-0 items-center justify-center rounded-full border',active?'border-green-600 bg-green-600 text-white':'border-gray-300')}>{active&&<Check size={12}/>}</span><span><b className="text-sm">{t}</b>{d&&<span className="mt-1 block text-xs leading-5 text-gray-500">{d}</span>}</span></button>})}</div>}
