import {Advisor,FinanceArticle} from '@/types'
// Fictional records for development. Replace with Supabase `advisors` rows in production.
export const advisors:Advisor[]=[
 {id:'ida-marie-snead',name:'Ida Marie Snead',initials:'IS',email:'ida.snead@advisoryrecord.test',reportUrl:'https://files.brokercheck.finra.org/individual/individual_3035093.pdf',specialties:['Wealth Management','Retirement','Investment Planning'],years:28,firmCount:2,licensedStates:6,sroCount:1,location:'Gillette, Wyoming · Nationwide virtual',fiduciary:true,availability:'Accepting clients',about:'Investment adviser representative associated with State Farm Investment Management Corp. and State Farm VP Management Corp., serving clients from Gillette, Wyoming.',approach:'Planning conversations shaped by investment goals, retirement priorities, and long-term financial needs.',credentials:['FINRA CRD #3035093','Registered with State Farm Investment Management Corp. since 08/25/2020','No disclosure events reported in the supplied BrokerCheck report'],communication:['Email','Phone']},
 {id:'jaime-lyn-raiten',name:'Jaime Lyn Raiten',initials:'JR',email:'jaime.raiten@advisoryrecord.test',reportUrl:'https://files.brokercheck.finra.org/individual/individual_4777678.pdf',specialties:['Investment Planning','Retirement','Wealth Management'],years:22,firmCount:1,licensedStates:0,sroCount:1,location:'Overland Park, Kansas · Nationwide virtual',fiduciary:false,availability:'Accepting clients',about:'Registered representative associated with Empower Financial Services, Inc., with a professional base in Overland Park, Kansas.',approach:'A structured investment conversation focused on understanding priorities, experience, and preferred communication.',credentials:['FINRA CRD #4777678','Registered with Empower Financial Services, Inc. since 09/03/2004','No disclosure events reported in the supplied BrokerCheck report'],communication:['Email','Phone']},
 {id:'andrea-marie-shenocca',name:'Andrea Marie Shenocca',initials:'AS',email:'andrea.shenocca@advisoryrecord.test',reportUrl:'https://files.brokercheck.finra.org/individual/individual_1273360.pdf',specialties:['Wealth Management','Retirement','Investment Planning','Estate Planning'],years:33,firmCount:1,licensedStates:18,sroCount:1,location:'Morristown, New Jersey · Nationwide virtual',fiduciary:true,availability:'Accepting clients',about:'Investment adviser representative and registered representative associated with Benjamin F. Edwards & Company, Inc., based in Morristown, New Jersey.',approach:'A coordinated planning approach for investment, retirement, and broader wealth decisions.',credentials:['FINRA CRD #1273360','Registered with Benjamin F. Edwards & Company since 07/02/2013','No disclosure events reported in the supplied BrokerCheck report'],communication:['Email','Phone']},
 {id:'anna-louise-lay',name:'Anna Louise Lay',initials:'AL',email:'anna.lay@advisoryrecord.test',reportUrl:'https://files.brokercheck.finra.org/individual/individual_3022366.pdf',specialties:['Wealth Management','Investment Planning','Retirement','Tax Planning'],years:25,firmCount:1,licensedStates:53,sroCount:4,location:'Beverly Hills, California · Nationwide virtual',fiduciary:true,availability:'Accepting clients',about:'Investment adviser representative and registered representative associated with Morgan Stanley, serving clients from Beverly Hills, California.',approach:'A broad wealth planning conversation built around investment goals, retirement, and personal priorities.',credentials:['FINRA CRD #3022366','Registered with Morgan Stanley since 03/10/2023','No disclosure events reported in the supplied BrokerCheck report'],communication:['Email','Phone']}
]
export const articles:FinanceArticle[]=[
 {category:'Markets',headline:'What changing rate expectations mean for long-term investors',source:'AdvisoryRecord Editorial',published:'12 min read',summary:'A measured guide to separating portfolio decisions from the noise of a single policy meeting.',url:'/insights'},
 {category:'Retirement',headline:'The questions worth asking before choosing a retirement income plan',source:'AdvisoryRecord Editorial',published:'8 min read',summary:'A framework for comparing flexibility, predictability, taxes, and longevity.',url:'/insights'},
 {category:'Wealth Planning',headline:'How to prepare for a first conversation with a financial advisor',source:'AdvisoryRecord Editorial',published:'6 min read',summary:'The documents, priorities, and questions that can make an introductory meeting more useful.',url:'/insights'},
 {category:'Risk',headline:'Risk tolerance and risk capacity are not the same thing',source:'AdvisoryRecord Editorial',published:'9 min read',summary:'Why both matter when shaping an investment approach you can live with.',url:'/insights'}
]
